prices:
  service:
    ping-service:
      status-ok: "I'm alive"
spring:
  datasource:
    url: jdbc:h2:file:./data/prices
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    initialization-mode: always